version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"